### ISSUE TITLE
Possible to add license

### ISSUE THREAD

**Issue by bergerx** [shadowofjoy/dcos-sdk-go#1]
We are thinking about using this in our company but there is no License information in the repo which prevents us to use the library.  If there are no licenses mentions its default would be proprietary.

Also, I'm seeing references to `github.com/dcos/dcos-sdk-go` but can't see that exist anymore, and prevents us to identify who is the original author. So if you are the original author and can add a Licencing info we'd be happy to use this repo and further contributions can be pushed to here.

**Comment by sbcharr** [comment]
Hi,

Thanks for showing interest on 'dcos-sdk-go' repo. This is my own endeavor
to build an sdk on top of dcos cosmos and marathon APIs to make it simple
for other developers, however, because of other priorities, I could not
give much attention to this of late. There is no License available for this
repo as this my personal repo and I don't think I have used any external
package except the cosmos and Marathon APIs. If those require a separate
license you may want to check with Mesosphere. Feel free to use and let me
know if I can help with something. Let me know if you find it useful.

I changed something at github a/c level and I think it breaks the repo.
Instead of 'github.com/dcos/dcos-sdk-go' now it should be '
github.com/squeakysimple/dcos-sdk-go', which is the same repo.

Regards,
SB

**Comment by bergerx** [comment]
Cool, would you mind to merge if we create a pull request to add some licence information like MIT to the repo. The lack of licensing information tend to block us using such open libraries.

We are thinking about using it in terraform marathon provider on our DC/OS clusters, you can see an early test here: https://github.com/PTC-Global/terraform-provider-marathon/pull/1/files

**Comment by sbcharr** [comment]
That should be fine.

**Comment by bergerx** [comment]
#3 solves this issue
